apiVersion: v1
kind: Service
metadata:
  name: ecommerce-product-api
  labels:
    run: ecommerce-product-api
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: ecommerce-product-api