apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-shopping-api
  labels:
    app: ecommerce-shopping-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-shopping-api
  template:
    metadata:
      labels:
        app: ecommerce-shopping-api
    spec:
      containers:
        - name: ecommerce-shopping-api
          image: loja/ecommerce-shopping-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: database_url
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: database_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: database_password
            - name: PRODUCT_API_URL
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-shopping-api-configmap
                  key: product_api_url
            - name: USER_API_URL
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-shopping-api-configmap
                  key: user_api_url