apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-user-api
  labels:
    app: ecommerce-user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-user-api
  template:
    metadata:
      labels:
        app: ecommerce-user-api
    spec:
      containers:
        - name: ecommerce-user-api
          image: loja/ecommerce-user-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: database_url
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: database_user
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: database_password