apiVersion: v1
kind: Service
metadata:
  name: ecommerce-user-api
  labels:
    run: ecommerce-user-api
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: ecommerce-user-api